default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password: 9511

development:
  <<: *default
  database: db/donadores_compulsivos_development

test:
  <<: *default
  database: db/donadores_compulsivos_test

production:
  <<: *default
  database: db/donadores_compulsivos_production
